### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [starkware-libs/crypto-cpp#16]
How do I compile the library "crypto_c_exports"? It should be straightforward but it really isn't.

**Comment by yuriymyronovych** [comment]
cmake
cd build
make all

**Comment by CNich** [comment]
On ubuntu, I went to the main directory and ran the presubmit.sh script, then did:

cmake .
make all

note, I had to go into the CMakeLists.txt and change the 3rd line from:

set(CMAKE_CXX_COMPILER /usr/bin/clang++-6.0) 
to 
set(CMAKE_CXX_COMPILER /usr/bin/clang++-14)
which depends on your version of clang, unless you set your environment variable

My build folder is empty but I am able to successfully use libcrypto_c_exports.so in other projects

**Comment by SpaceMonkeyForever** [comment]
I didn't test these answers (I moved on) but thanks for replying.
